name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@v3.13
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          repositories_affiliations: owner, collaborator, organization_member
          base: header
          debug: yes
          config_display: columns
          config_order: base.header, achievements, music, habits, followup
          config_timezone: Europe/Paris # Set timezone
          plugin_followup: yes
          plugin_followup_sections: repositories, user #
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_music: yes
          plugin_music_provider: spotify # Use Spotify as provider
          plugin_music_mode: recent      # Set plugin mode
          plugin_music_limit: 4          # Limit to 4 entries
          plugin_music_played_at: yes    # Show timestamp (for spotify only)
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
